framework:
    messenger:
        failure_transport: failed

        transports:
            # Using Redis for async transport
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            # Scheduler messages transport
            scheduler_default:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

            # Failed messages transport
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route scheduled messages to scheduler transport
            'Symfony\Component\Scheduler\Messenger\ScheduledStamp': scheduler_default
            # Route your custom messages to async transport
            'App\Message\ParseWiktionaryArticlesMessage': async
