nelmio_api_doc:
  documentation:
    info:
      title: Language Detection API
      description: Language Detection API
      version: 1.0.1
    servers:
      - url: "https://%env(string:DOMAIN)%"
        description: "API Server"
  areas:
    path_patterns:
      - ^/api(?!/doc)